# Generated by Django 5.1.6 on 2025-03-12 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bank_account", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankaccount",
            old_name="account_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="bankaccount",
            old_name="account_number",
            new_name="number",
        ),
        migrations.RenameField(
            model_name="bankaccount",
            old_name="user_id",
            new_name="user",
        ),
    ]
