# Generated by Django 5.1.6 on 2025-03-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="transaction",
            old_name="category_id",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="transaction",
            old_name="user_id",
            new_name="user",
        ),
    ]
