# Generated by Django 5.1.3 on 2025-01-02 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="transaction",
            name="transaction_name",
            field=models.TextField(default=""),
        ),
    ]
