# Generated by Django 5.1.3 on 2025-01-02 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
        ("transaction", "0002_transaction_transaction_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="category_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="category.category"
            ),
        ),
        migrations.DeleteModel(
            name="Category",
        ),
    ]
