# Generated by Django 5.1.3 on 2025-01-02 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("transaction", "0003_alter_transaction_category_id_delete_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="transaction_name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
