# Generated by Django 5.1.3 on 2025-01-02 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "transaction",
            "0006_remove_transaction_created_at_transaction_create_at_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="create_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
