# Generated by Django 5.1.6 on 2025-02-18 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="category",
            name="category_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="category.categorytype"
            ),
        ),
    ]
