# Generated by Django 5.1.3 on 2025-01-02 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0002_alter_category_user_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="user_id",
            new_name="user",
        ),
    ]
