# Generated by Django 5.1.3 on 2025-01-02 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0003_rename_user_id_category_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="user",
            new_name="user_id",
        ),
    ]
