# Generated by Django 5.1.6 on 2025-03-05 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0004_categorytype_alter_category_category_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_name",
            new_name="name",
        ),
    ]
