# Generated by Django 5.1.6 on 2025-03-05 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0005_rename_category_name_category_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="category_type",
            new_name="type",
        ),
    ]
