# Generated by Django 5.1.6 on 2025-03-06 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0006_rename_category_type_category_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="user_id",
            new_name="user",
        ),
    ]
