# Generated by Django 5.1.3 on 2024-12-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_name",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.IntegerField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="wallet",
            name="wallet_name",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
