# Generated by Django 5.1.3 on 2024-12-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_alter_bankaccount_account_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bankaccount",
            name="account_number",
            field=models.IntegerField(),
        ),
    ]
