# Generated by Django 5.1.3 on 2025-01-02 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0004_alter_bankaccount_account_number"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BankAccount",
        ),
    ]
