# Generated by Django 5.1.4 on 2025-01-05 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("possession_status", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="possessionstatus",
            name="description",
            field=models.TextField(max_length=100),
        ),
    ]
