name: budget_planner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]



jobs:
  build:
    services:
      postgres:
        image: postgres:17.2
        env:
          POSTGRES_USER: ${{ vars.POSTGRES_USER }}
          POSTGRES_NAME:  ${{ vars.POSTGRES_NAME }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry
    - name: Install Dependencies
      run: |
        poetry install
      env:
        POETRY_VIRTUALENVS_CREATE: false
    - name: Run Django Test
      run: |
        coverage run manage.py test
        coverage report
        coverage xml
      env:
        POSTGRES_NAME: ${{ vars.POSTGRES_NAME }}
        POSTGRES_USER: ${{ vars.POSTGRES_USER }}
        POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        POSTGRES_HOST: ${{ vars.POSTGRES_HOST }}
        POSTGRES_PORT: ${{ vars.POSTGRES_PORT }}
    - name: Upload coverage report
      uses: codecov/codecov-action@v4
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Lint with ruff
      run: |
        ruff check .
